//! Phase-3 gate: `anybuild generate` output must match every committed
//! example golden (version-masked), driven by Rust detection end-to-end.
//!
//! Regeneration: `ANYBUILD_UPDATE_FIXTURES=1` rewrites `examples/*/Anybuild`
//! and the example-derived `anybuild` texts in `fixtures/manifest.json`
//! (see `scripts/update_fixtures.sh`). Synthetic-case texts are
//! hand-authored fixtures and are left untouched.

use std::path::{Path, PathBuf};

const EXPECTED_GOLDENS: usize = 80;
const UPDATE_FIXTURES_ENV: &str = "ANYBUILD_UPDATE_FIXTURES";

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .unwrap()
}

fn mask_version(text: &str) -> String {
    let mut out = Vec::new();
    for line in text.lines() {
        if line.starts_with("# Generated by Anybuild v") {
            out.push("# Generated by Anybuild v<VERSION>".to_owned());
        } else {
            out.push(line.to_owned());
        }
    }
    let mut joined = out.join("\n");
    if text.ends_with('\n') {
        joined.push('\n');
    }
    joined
}

const SUBDIR_EXAMPLES: &[(&str, &str)] = &[
    ("node-npm-file-subdir", "apps/dashboard"),
    ("node-pnpm-workspace-subdir", "apps/dashboard"),
];

fn example_env(name: &str) -> Vec<(&'static str, &'static str)> {
    if name == "php-wordpress-empty" {
        vec![
            ("ANYBUILD_WP_VERSION", "latest"),
            ("ANYBUILD_PHPIX", "true"),
        ]
    } else {
        vec![]
    }
}

#[test]
fn generated_files_match_examples() {
    let root = repo_root();
    let examples = root.join("examples");
    let update = std::env::var(UPDATE_FIXTURES_ENV).as_deref() == Ok("1");
    let mut updated = 0usize;
    let mut checked = 0usize;
    let mut failures: Vec<String> = Vec::new();

    let mut dirs: Vec<PathBuf> = std::fs::read_dir(&examples)
        .unwrap()
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.join("Anybuild").is_file())
        .collect();
    dirs.sort();
    assert_eq!(
        dirs.len(),
        EXPECTED_GOLDENS,
        "golden coverage changed; review the examples and update the pinned count intentionally"
    );

    for example_dir in dirs {
        let name = example_dir
            .file_name()
            .unwrap()
            .to_string_lossy()
            .into_owned();
        let subdir = SUBDIR_EXAMPLES
            .iter()
            .find(|(n, _)| *n == name)
            .map(|(_, s)| *s);
        let env = example_env(&name);
        for (key, value) in &env {
            std::env::set_var(key, value);
        }

        let result = generate_for(&example_dir, subdir);

        for (key, _) in &env {
            std::env::remove_var(key);
        }

        let generated = match result {
            Ok(text) => text,
            Err(err) => {
                failures.push(format!("{name}: {err:#}"));
                continue;
            }
        };
        let expected = std::fs::read_to_string(example_dir.join("Anybuild")).unwrap();
        if update {
            if mask_version(&generated) != mask_version(&expected) {
                updated += 1;
                std::fs::write(example_dir.join("Anybuild"), &generated).unwrap();
            }
            checked += 1;
        } else if mask_version(&generated) != mask_version(&expected) {
            failures.push(format!("{name}: generated Anybuild differs"));
        } else {
            checked += 1;
        }
    }

    if update {
        assert!(
            failures.is_empty(),
            "cannot update goldens, {} example(s) failed to generate:\n{}",
            failures.len(),
            failures.join("\n")
        );
        let manifest_updated = update_manifest_anybuild_texts(&root);
        eprintln!(
            "goldens: rewrote {checked} example(s) ({updated} changed); \
             manifest anybuild texts: {manifest_updated} changed"
        );
        assert_eq!(checked, EXPECTED_GOLDENS);
        return;
    }

    eprintln!("goldens: {checked} matched");
    if !failures.is_empty() {
        panic!(
            "{} golden(s) failed:\n{}",
            failures.len(),
            failures.join("\n")
        );
    }
    assert_eq!(checked, EXPECTED_GOLDENS);
}

/// Rewrite the `anybuild` text of every example-derived manifest case with
/// fresh `generate` output. The manifest convention (from the original
/// Python dump) omits the baked `name = "..."` argument — the case config
/// carries the name — so it is stripped here. Synthetic-case texts are
/// hand-authored and left untouched.
fn update_manifest_anybuild_texts(root: &Path) -> usize {
    let manifest_path = root.join("fixtures/manifest.json");
    let mut raw: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&manifest_path).unwrap()).unwrap();
    let cases = raw["cases"].as_array_mut().expect("cases array");
    let mut changed = 0usize;
    for case in cases.iter_mut() {
        let workspace = case["workspace"]
            .as_str()
            .expect("workspace string")
            .to_owned();
        if !workspace.starts_with("examples/") {
            continue;
        }
        case.as_object_mut().expect("case object").remove("shipit");
        let name = case["name"].as_str().expect("name string");
        let base_name = name.strip_suffix("__cross").unwrap_or(name);
        let subdir = case["subdir"].as_str().map(str::to_owned);
        let env = example_env(base_name);
        for (key, value) in &env {
            std::env::set_var(key, value);
        }
        let generated = generate_for(&root.join(&workspace), subdir.as_deref());
        for (key, _) in &env {
            std::env::remove_var(key);
        }
        let generated = generated
            .unwrap_or_else(|err| panic!("{name}: generate failed during update: {err:#}"));
        let text = strip_baked_name(&generated);
        if case["anybuild"].as_str() != Some(text.as_str()) {
            changed += 1;
        }
        case["anybuild"] = serde_json::Value::String(text);
    }
    std::fs::write(
        &manifest_path,
        anybuild_common::pyjson::to_python_json(&raw),
    )
    .unwrap();
    changed
}

/// Remove the single `, name = "..."` argument generate bakes into the
/// serve call.
fn strip_baked_name(text: &str) -> String {
    let Some(start) = text.find(", name = \"") else {
        return text.to_owned();
    };
    let value_start = start + ", name = \"".len();
    let Some(quote_offset) = text[value_start..].find('"') else {
        return text.to_owned();
    };
    let end = value_start + quote_offset + 1;
    format!("{}{}", &text[..start], &text[end..])
}

fn generate_for(workspace: &Path, subdir: Option<&str>) -> anyhow::Result<String> {
    let tmp = tempfile::tempdir()?;
    let out = tmp.path().join("Anybuild.generated");
    let mut command = std::process::Command::new(env!("CARGO_BIN_EXE_anybuild"));
    command.arg("generate").arg(workspace);
    if let Some(subdir) = subdir {
        command.args(["--subdir", subdir]);
    }
    command.arg("--out").arg(&out);
    // Env vars set by the caller are inherited.
    let output = command.output()?;
    if !output.status.success() {
        anyhow::bail!(
            "generate failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );
    }
    Ok(std::fs::read_to_string(&out)?)
}
