exec:
  filename: generated/exec.go
model:
  filename: models/generated.go
  package: models

autobind:
  - github.com/wasmerio/anybuild/examples/go-graphql/models

models:
  ReviewInput:
    model: models.Review
  Starship:
    fields:
      length:
        resolver: true
