//! Anybuild file generation (port of `generator.py`).

use anyhow::{anyhow, Result};

/// The workspace version (root Cargo.toml) is the single version source;
/// release-please bumps it via the x-release-please-version marker.
pub fn anybuild_version() -> &'static str {
    env!("CARGO_PKG_VERSION")
}

pub struct Entrypoint {
    pub config: (&'static str, &'static str),
    pub build: (&'static str, &'static str),
    pub serve: (&'static str, &'static str),
}

const STATICFILE_SERVE: (&str, &str) = ("//anybuild/tools:staticfile.bzl", "staticfile_serve");

/// Mirror of `STARLARK_ENTRYPOINTS` in generator.py.
pub fn entrypoint(provider: &str) -> Result<Entrypoint> {
    let ep = match provider {
        "python" => Entrypoint {
            config: ("//anybuild/tools:python.bzl", "python_config"),
            build: ("//anybuild/tools:python.bzl", "python_build"),
            serve: ("//anybuild/tools:python.bzl", "python_serve"),
        },
        "staticfile" => Entrypoint {
            config: ("//anybuild/tools:staticfile.bzl", "staticfile_config"),
            build: ("//anybuild/tools:staticfile.bzl", "staticfile_build"),
            serve: STATICFILE_SERVE,
        },
        "hugo" => Entrypoint {
            config: ("//anybuild/tools:hugo.bzl", "hugo_config"),
            build: ("//anybuild/tools:hugo.bzl", "hugo_build"),
            serve: STATICFILE_SERVE,
        },
        "mkdocs" => Entrypoint {
            config: ("//anybuild/tools:mkdocs.bzl", "mkdocs_config"),
            build: ("//anybuild/tools:mkdocs.bzl", "mkdocs_build"),
            serve: STATICFILE_SERVE,
        },
        "jekyll" => Entrypoint {
            config: ("//anybuild/tools:jekyll.bzl", "jekyll_config"),
            build: ("//anybuild/tools:jekyll.bzl", "jekyll_build"),
            serve: STATICFILE_SERVE,
        },
        "node-static" => Entrypoint {
            config: ("//anybuild/tools:node_static.bzl", "nodestatic_config"),
            build: ("//anybuild/tools:node_static.bzl", "nodestatic_build"),
            serve: STATICFILE_SERVE,
        },
        "go" => Entrypoint {
            config: ("//anybuild/tools:go.bzl", "go_config"),
            build: ("//anybuild/tools:go.bzl", "go_build"),
            serve: ("//anybuild/tools:go.bzl", "go_serve"),
        },
        "php" => Entrypoint {
            config: ("//anybuild/tools:php.bzl", "php_config"),
            build: ("//anybuild/tools:php.bzl", "php_build"),
            serve: ("//anybuild/tools:php.bzl", "php_serve"),
        },
        "wordpress" => Entrypoint {
            config: ("//anybuild/tools:wordpress.bzl", "wordpress_config"),
            build: ("//anybuild/tools:wordpress.bzl", "wordpress_build"),
            serve: ("//anybuild/tools:wordpress.bzl", "wordpress_serve"),
        },
        "node" => Entrypoint {
            config: ("//anybuild/tools:node.bzl", "node_config"),
            build: ("//anybuild/tools:node.bzl", "node_build"),
            serve: ("//anybuild/tools:node.bzl", "node_serve"),
        },
        "laravel" => Entrypoint {
            config: ("//anybuild/tools:laravel.bzl", "laravel_config"),
            build: ("//anybuild/tools:laravel.bzl", "laravel_build"),
            serve: ("//anybuild/tools:laravel.bzl", "laravel_serve"),
        },
        other => {
            return Err(anyhow!(
                "No Starlark provider entrypoint registered for {other:?}"
            ))
        }
    };
    Ok(ep)
}

/// Port of `generate_anybuild_loader`: byte-identical output.
pub fn generate_anybuild_loader(
    entrypoint: &Entrypoint,
    subdir: Option<&str>,
    name: Option<&str>,
    schema: u32,
    config: &serde_json::Value,
    runtime_dependencies: &[String],
) -> String {
    let (config_module, config_function) = entrypoint.config;
    let (build_module, build_function) = entrypoint.build;
    let (serve_module, serve_function) = entrypoint.serve;
    let mut out: Vec<String> = vec![
        format!(
            "# Generated by Anybuild v{} — https://anybuild.run",
            anybuild_version()
        ),
        "# This file is yours to edit: add steps or override the serve below.".to_owned(),
        String::new(),
    ];
    debug_assert_eq!(config_module, build_module);
    if build_module == serve_module {
        out.push(format!(
            "load(\"{build_module}\", \"{build_function}\", \"{config_function}\", \"{serve_function}\")"
        ));
    } else {
        out.push(format!(
            "load(\"{build_module}\", \"{build_function}\", \"{config_function}\")"
        ));
        out.push(format!("load(\"{serve_module}\", \"{serve_function}\")"));
    }
    out.push(String::new());
    if let Some(subdir) = subdir {
        out.push(format!(
            "app_subdir = {}",
            serde_json::to_string(subdir).expect("string serializes")
        ));
        out.push(String::new());
    }
    out.extend(serialize_config(config_function, schema, config));
    out.push(String::new());
    if !runtime_dependencies.is_empty() {
        out.push("runtime_dependencies = [".to_owned());
        for dependency in runtime_dependencies {
            out.push(format!("    {},", runtime_dependency_literal(dependency)));
        }
        out.push("]".to_owned());
        out.push(String::new());
    }
    out.push(format!("build = {build_function}(config)"));
    out.push(String::new());
    let mut serve_args: Vec<String> = vec!["config".to_owned(), "build".to_owned()];
    if let Some(name) = name {
        // Baked in so the serve name doesn't drift with the directory the
        // checkout happens to live in.
        serve_args.push(format!(
            "name = {}",
            serde_json::to_string(name).expect("string serializes")
        ));
    }
    if !runtime_dependencies.is_empty() {
        serve_args.push("extra_deps = runtime_dependencies".to_owned());
    }
    out.push(format!("{serve_function}({})", serve_args.join(", ")));
    out.push(String::new());
    out.join("\n")
}

fn runtime_dependency_literal(spec: &str) -> String {
    let (name, version) = match spec.rsplit_once('@') {
        Some((name, version)) if !name.is_empty() && !version.is_empty() => (name, Some(version)),
        _ => (spec, None),
    };
    let name = serde_json::to_string(name).expect("dependency name serializes");
    match version {
        Some(version) => format!(
            "dep({name}, {})",
            serde_json::to_string(version).expect("dependency version serializes")
        ),
        None => format!("dep({name})"),
    }
}

/// Port of `generate_anybuild`: entrypoint lookup + the baked name.
pub fn generate_anybuild(
    provider: &str,
    config_name: Option<&str>,
    subdir: Option<&str>,
    schema: u32,
    config: &serde_json::Value,
    runtime_dependencies: &[String],
) -> Result<String> {
    let ep = entrypoint(provider)?;
    Ok(generate_anybuild_loader(
        &ep,
        subdir,
        config_name,
        schema,
        config,
        runtime_dependencies,
    ))
}

fn serialize_config(function: &str, schema: u32, config: &serde_json::Value) -> Vec<String> {
    let mut out = vec![
        format!("config = {function}("),
        format!("    schema = {schema},"),
    ];
    if let Some(config) = config.as_object() {
        for (key, value) in config {
            out.push(format!("    {key} = {},", starlark_literal(value, 1)));
        }
    }
    out.push(")".to_owned());
    out
}

fn starlark_literal(value: &serde_json::Value, indent: usize) -> String {
    use serde_json::Value;
    match value {
        Value::Null => "None".to_owned(),
        Value::Bool(true) => "True".to_owned(),
        Value::Bool(false) => "False".to_owned(),
        Value::Number(number) => number.to_string(),
        Value::String(value) => serde_json::to_string(value).expect("string serializes"),
        Value::Array(values) if values.is_empty() => "[]".to_owned(),
        Value::Array(values) => {
            let child = "    ".repeat(indent + 1);
            let close = "    ".repeat(indent);
            let values = values
                .iter()
                .map(|value| format!("{child}{},", starlark_literal(value, indent + 1)))
                .collect::<Vec<_>>()
                .join("\n");
            format!("[\n{values}\n{close}]")
        }
        Value::Object(values) if values.is_empty() => "{}".to_owned(),
        Value::Object(values) => {
            let child = "    ".repeat(indent + 1);
            let close = "    ".repeat(indent);
            let values = values
                .iter()
                .map(|(key, value)| {
                    format!(
                        "{child}{}: {},",
                        serde_json::to_string(key).expect("key serializes"),
                        starlark_literal(value, indent + 1)
                    )
                })
                .collect::<Vec<_>>()
                .join("\n");
            format!("{{\n{values}\n{close}}}")
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn config_literals_are_deterministic_starlark() {
        let config = serde_json::json!({
            "enabled": true,
            "missing": null,
            "items": ["one", false],
            "mapping": {"answer": 42},
        });
        let generated = generate_anybuild("node", Some("app"), None, 1, &config, &[]).unwrap();
        assert!(generated.contains("    enabled = True,\n"));
        assert!(generated.contains("    missing = None,\n"));
        assert!(generated.contains("    items = [\n        \"one\",\n        False,\n    ],\n"));
        assert!(generated.contains("    mapping = {\n        \"answer\": 42,\n    },\n"));
        assert_eq!(
            generated,
            generate_anybuild("node", Some("app"), None, 1, &config, &[]).unwrap()
        );
    }

    #[test]
    fn runtime_dependencies_are_rendered_as_editable_dep_calls() {
        let generated = generate_anybuild(
            "python",
            Some("app"),
            None,
            1,
            &serde_json::json!({}),
            &["ffmpeg".to_owned(), "pandoc@3.6".to_owned()],
        )
        .unwrap();

        assert!(generated.contains(
            "runtime_dependencies = [\n    dep(\"ffmpeg\"),\n    dep(\"pandoc\", \"3.6\"),\n]\n"
        ));
        assert!(generated.contains("build = python_build(config)\n"));
        assert!(generated.contains(
            "python_serve(config, build, name = \"app\", extra_deps = runtime_dependencies)\n"
        ));
    }

    #[test]
    fn scoped_runtime_dependency_without_version_is_not_split() {
        assert_eq!(
            runtime_dependency_literal("@scope/package"),
            "dep(\"@scope/package\")"
        );
        assert_eq!(
            runtime_dependency_literal("@scope/package@1.2"),
            "dep(\"@scope/package\", \"1.2\")"
        );
    }
}
