//! Anybuild file generation (port of `generator.py`).

use anyhow::{anyhow, Result};

/// The workspace version (root Cargo.toml) is the single version source;
/// release-please bumps it via the x-release-please-version marker.
pub fn anybuild_version() -> &'static str {
    env!("CARGO_PKG_VERSION")
}

pub struct Entrypoint {
    pub build: (&'static str, &'static str),
    pub serve: (&'static str, &'static str),
    /// The deployment identity the generated file passes to the serve when
    /// it differs from the serve function's default.
    pub provider: Option<&'static str>,
}

const STATICFILE_SERVE: (&str, &str) = ("//anybuild/tools:staticfile.bzl", "staticfile_serve");

/// Mirror of `STARLARK_ENTRYPOINTS` in generator.py.
pub fn entrypoint(provider: &str) -> Result<Entrypoint> {
    let ep = match provider {
        "python" => Entrypoint {
            build: ("//anybuild/tools:python.bzl", "python_build"),
            serve: ("//anybuild/tools:python.bzl", "python_serve"),
            provider: None,
        },
        "staticfile" => Entrypoint {
            build: ("//anybuild/tools:staticfile.bzl", "staticfile_build"),
            serve: STATICFILE_SERVE,
            provider: None,
        },
        "hugo" => Entrypoint {
            build: ("//anybuild/tools:hugo.bzl", "hugo_build"),
            serve: STATICFILE_SERVE,
            provider: Some("hugo"),
        },
        "mkdocs" => Entrypoint {
            build: ("//anybuild/tools:mkdocs.bzl", "mkdocs_build"),
            serve: STATICFILE_SERVE,
            provider: Some("mkdocs"),
        },
        "jekyll" => Entrypoint {
            build: ("//anybuild/tools:jekyll.bzl", "jekyll_build"),
            serve: STATICFILE_SERVE,
            provider: Some("jekyll"),
        },
        "node-static" => Entrypoint {
            build: ("//anybuild/tools:node_static.bzl", "nodestatic_build"),
            serve: STATICFILE_SERVE,
            provider: Some("node-static"),
        },
        "go" => Entrypoint {
            build: ("//anybuild/tools:go.bzl", "go_build"),
            serve: ("//anybuild/tools:go.bzl", "go_serve"),
            provider: None,
        },
        "php" => Entrypoint {
            build: ("//anybuild/tools:php.bzl", "php_build"),
            serve: ("//anybuild/tools:php.bzl", "php_serve"),
            provider: None,
        },
        "wordpress" => Entrypoint {
            build: ("//anybuild/tools:wordpress.bzl", "wordpress_build"),
            serve: ("//anybuild/tools:wordpress.bzl", "wordpress_serve"),
            provider: None,
        },
        "node" => Entrypoint {
            build: ("//anybuild/tools:node.bzl", "node_build"),
            serve: ("//anybuild/tools:node.bzl", "node_serve"),
            provider: None,
        },
        "laravel" => Entrypoint {
            build: ("//anybuild/tools:laravel.bzl", "laravel_build"),
            serve: ("//anybuild/tools:laravel.bzl", "laravel_serve"),
            provider: None,
        },
        other => {
            return Err(anyhow!(
                "No Starlark provider entrypoint registered for {other:?}"
            ))
        }
    };
    Ok(ep)
}

/// Port of `generate_anybuild_loader`: byte-identical output.
pub fn generate_anybuild_loader(
    entrypoint: &Entrypoint,
    subdir: Option<&str>,
    name: Option<&str>,
) -> String {
    let (build_module, build_function) = entrypoint.build;
    let (serve_module, serve_function) = entrypoint.serve;
    let mut out: Vec<String> = vec![
        format!(
            "# Generated by Anybuild v{} — https://github.com/wasmerio/anybuild",
            anybuild_version()
        ),
        "# This file is yours to edit: add steps or override the serve below.".to_owned(),
        String::new(),
    ];
    if build_module == serve_module {
        out.push(format!(
            "load(\"{build_module}\", \"{build_function}\", \"{serve_function}\")"
        ));
    } else {
        out.push(format!("load(\"{build_module}\", \"{build_function}\")"));
        out.push(format!("load(\"{serve_module}\", \"{serve_function}\")"));
    }
    out.push(String::new());
    if let Some(subdir) = subdir {
        out.push(format!(
            "app_subdir = {}",
            serde_json::to_string(subdir).expect("string serializes")
        ));
        out.push(String::new());
    }
    out.push(format!("build = {build_function}(config)"));
    out.push(String::new());
    let mut serve_args: Vec<String> = vec!["config".to_owned(), "build".to_owned()];
    if let Some(name) = name {
        // Baked in so the serve name doesn't drift with the directory the
        // checkout happens to live in.
        serve_args.push(format!(
            "name = {}",
            serde_json::to_string(name).expect("string serializes")
        ));
    }
    if let Some(provider) = entrypoint.provider {
        serve_args.push(format!("provider = \"{provider}\""));
    }
    out.push(format!("{serve_function}({})", serve_args.join(", ")));
    out.push(String::new());
    out.join("\n")
}

/// Port of `generate_anybuild`: entrypoint lookup + the baked name.
pub fn generate_anybuild(
    provider: &str,
    config_name: Option<&str>,
    subdir: Option<&str>,
) -> Result<String> {
    let ep = entrypoint(provider)?;
    Ok(generate_anybuild_loader(&ep, subdir, config_name))
}
