//! Wasmer manifest (wasmer.toml) generation.

use crate::builders::base::BuildBackend;
use crate::runners::wasmer::mapper::{get_dependency_version, get_mapper_item, REWRITE_BINARIES};
use crate::types::serve::Serve;
use anyhow::{Context, Result};
use std::collections::HashMap;
use std::path::{Path, PathBuf};

fn parse_dependency_ref(dep_ref: &str) -> (String, String) {
    if let Some((name, version)) = dep_ref.split_once('@') {
        (name.to_string(), version.to_string())
    } else {
        (dep_ref.to_string(), "*".to_string())
    }
}

/// Check if a file is a WebAssembly module.
pub fn is_wasm_file(path: &Path) -> bool {
    if let Ok(mut file) = std::fs::File::open(path) {
        use std::io::Read;
        let mut magic = [0u8; 4];
        if file.read_exact(&mut magic).is_ok() {
            return magic == [0x00, 0x61, 0x73, 0x6d]; // \0asm
        }
    }
    false
}

/// Find a file in mounts by checking serve paths.
pub fn find_file_in_mounts(
    serve: &Serve,
    backend: &dyn BuildBackend,
    program: &str,
) -> Option<PathBuf> {
    let mounts = serve.mounts.as_ref()?;

    for mount in mounts {
        let serve_path = mount.serve_path.to_string_lossy();
        if let Some(relative) = program.strip_prefix(serve_path.as_ref()) {
            let artifact_path = backend.get_artifact_mount_path(&mount.name);
            let full_path = artifact_path.join(relative.trim_start_matches('/'));
            if full_path.exists() {
                return Some(full_path);
            }
        }
    }

    None
}

/// Generate wasmer.toml manifest.
pub fn generate_manifest(serve: &Serve, backend: &dyn BuildBackend) -> Result<String> {
    let mut lines = vec![
        "# Generated by Shipit".to_string(),
        "".to_string(),
        "[package]".to_string(),
        "entrypoint = \"start\"".to_string(),
        "".to_string(),
    ];

    // Map dependencies
    let mut binaries: HashMap<String, (String, HashMap<String, String>)> = HashMap::new();
    let mut deps_lines = vec!["[dependencies]".to_string()];

    // Add bash if prepare steps exist
    let mut has_bash = false;
    if serve.prepare.is_some() {
        deps_lines.push("\"wasmer/bash\" = \"=1.0.24\"".to_string());
        has_bash = true;
    }

    // Process package dependencies
    for pkg in &serve.deps {
        // Get the package name and version
        let name = &pkg.name;
        let version = pkg.version.as_deref();
        let architecture = pkg.architecture.map(|arch| match arch {
            crate::types::package::Architecture::Bit64 => "64bit",
            crate::types::package::Architecture::Bit32 => "32bit",
        });

        if let Some(mapper_item) = get_mapper_item(name) {
            // Get dependency string
            let dep_str = get_dependency_version(name, version, architecture)
                .with_context(|| format!("Failed to resolve dependency: {}", name))?;

            let (dep_name, dep_version) = parse_dependency_ref(&dep_str);

            // Add to dependencies
            deps_lines.push(format!("\"{}\" = \"{}\"", dep_name, dep_version));

            // Track binaries
            if !mapper_item.scripts.is_empty() {
                for script in &mapper_item.scripts {
                    let module = format!("{}:{}", dep_name, script);
                    binaries.insert(script.clone(), (module, mapper_item.env.clone()));
                }
            }

            if !mapper_item.aliases.is_empty() {
                for (alias, script) in &mapper_item.aliases {
                    let module = format!("{}:{}", dep_name, script);
                    binaries.insert(alias.clone(), (module, mapper_item.env.clone()));
                }
            }
        }
    }

    if deps_lines.len() > 1 || has_bash {
        lines.extend(deps_lines);
        lines.push("".to_string());
    }

    // Filesystem mappings
    if let Some(mounts) = &serve.mounts {
        lines.push("[fs]".to_string());
        for mount in mounts {
            let artifact_path = backend.get_artifact_mount_path(&mount.name);
            lines.push(format!(
                "\"{}\" = \"{}\"",
                mount.serve_path.display(),
                artifact_path.display()
            ));
        }
        lines.push("".to_string());
    }

    // WebAssembly modules
    let mut modules: HashMap<String, PathBuf> = HashMap::new();

    // Generate commands
    for (cmd_name, cmd_str) in &serve.commands {
        // Parse command
        let parts = match shlex::split(cmd_str) {
            Some(p) => p,
            None => {
                eprintln!("Warning: Failed to parse command: {}", cmd_str);
                continue;
            }
        };

        if parts.is_empty() {
            continue;
        }

        let mut program = parts[0].clone();
        let mut args = parts[1..].to_vec();
        let mut env = HashMap::new();

        // Merge serve environment
        if let Some(serve_env) = &serve.env {
            env.extend(serve_env.clone());
        }

        // Check binary rewriting
        if let Some(rewritten) = REWRITE_BINARIES.get(program.as_str()) {
            let rewrite_parts: Vec<&str> = rewritten.split_whitespace().collect();
            program = rewrite_parts[0].to_string();
            if rewrite_parts.len() > 1 {
                args.insert(0, rewrite_parts[1..].join(" "));
            }
        }

        // Determine module
        let module_name = if let Some((dependency_module, bin_env)) = binaries.get(&program) {
            // Binary from dependency
            env.extend(bin_env.clone());
            dependency_module.clone()
        } else if program.starts_with('/') {
            // Absolute path - check if it's a wasm module
            if let Some(file_path) = find_file_in_mounts(serve, backend, &program) {
                if is_wasm_file(&file_path) {
                    let module_name = program
                        .replace('/', "_")
                        .trim_start_matches('_')
                        .to_string();
                    modules.insert(module_name.clone(), file_path);
                    module_name
                } else {
                    eprintln!("Warning: {} is not a WebAssembly module", program);
                    continue;
                }
            } else {
                eprintln!("Warning: {} not found in mounts", program);
                continue;
            }
        } else {
            // Relative or bare command - assume it's available
            program.clone()
        };

        // Build command entry
        lines.push("[[command]]".to_string());
        lines.push(format!("name = \"{}\"", cmd_name));
        lines.push(format!("module = \"{}\"", module_name));
        lines.push("runner = \"wasi\"".to_string());

        // Annotations
        lines.push("[command.annotations.wasi]".to_string());

        if let Some(cwd) = &serve.cwd {
            lines.push(format!("cwd = \"{}\"", cwd));
        }

        if !args.is_empty() {
            lines.push(format!("main-args = {:?}", args));
        }

        if !env.is_empty() {
            let mut env_items: Vec<String> =
                env.iter().map(|(k, v)| format!("{}={}", k, v)).collect();
            env_items.sort();
            lines.push(format!("env = {:?}", env_items));
        }

        lines.push("".to_string());
    }

    // Add modules section if any
    if !modules.is_empty() {
        for (name, path) in modules {
            lines.push("[[module]]".to_string());
            lines.push(format!("name = \"{}\"", name));
            lines.push(format!("source = \"{}\"", path.display()));
            lines.push("".to_string());
        }
    }

    Ok(lines.join("\n"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_is_wasm_file() {
        // Test with non-existent file
        assert!(!is_wasm_file(Path::new("/nonexistent.wasm")));
    }

    #[test]
    fn test_find_file_in_mounts_no_mounts() {
        use crate::builders::local::LocalBuildBackend;

        let backend = LocalBuildBackend::new(PathBuf::from("/test"), PathBuf::from("/test/assets"));

        let serve = Serve::new("test", "test", vec![], vec![], HashMap::new());

        let result = find_file_in_mounts(&serve, &backend, "/app/main.wasm");
        assert!(result.is_none());
    }

    #[test]
    fn test_generate_manifest_simple() {
        use crate::builders::local::LocalBuildBackend;

        let backend = LocalBuildBackend::new(PathBuf::from("/test"), PathBuf::from("/test/assets"));

        let mut commands = HashMap::new();
        commands.insert("start".to_string(), "python -m http.server".to_string());

        let serve = Serve::new("test", "python", vec![], vec![], commands);

        let manifest = generate_manifest(&serve, &backend).unwrap();
        assert!(manifest.contains("[package]"));
        assert!(manifest.contains("entrypoint"));
    }
}
