//! Phase-3 gate: `shipit generate` output must match every committed
//! example golden (version-masked), driven by Rust detection end-to-end.

use std::path::{Path, PathBuf};

const EXPECTED_GOLDENS: usize = 80;

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .unwrap()
}

fn mask_version(text: &str) -> String {
    let mut out = Vec::new();
    for line in text.lines() {
        if line.starts_with("# Generated by Shipit v") {
            out.push("# Generated by Shipit v<VERSION>".to_owned());
        } else {
            out.push(line.to_owned());
        }
    }
    let mut joined = out.join("\n");
    if text.ends_with('\n') {
        joined.push('\n');
    }
    joined
}

const SUBDIR_EXAMPLES: &[(&str, &str)] = &[
    ("node-npm-file-subdir", "apps/dashboard"),
    ("node-pnpm-workspace-subdir", "apps/dashboard"),
];

fn example_env(name: &str) -> Vec<(&'static str, &'static str)> {
    if name == "php-wordpress-empty" {
        vec![("SHIPIT_WP_VERSION", "latest"), ("SHIPIT_PHPIX", "true")]
    } else {
        vec![]
    }
}

#[test]
fn generated_files_match_examples() {
    let root = repo_root();
    let examples = root.join("examples");
    let mut checked = 0usize;
    let mut failures: Vec<String> = Vec::new();

    let mut dirs: Vec<PathBuf> = std::fs::read_dir(&examples)
        .unwrap()
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.join("Shipit").is_file())
        .collect();
    dirs.sort();
    assert_eq!(
        dirs.len(),
        EXPECTED_GOLDENS,
        "golden coverage changed; review the examples and update the pinned count intentionally"
    );

    for example_dir in dirs {
        let name = example_dir
            .file_name()
            .unwrap()
            .to_string_lossy()
            .into_owned();
        let subdir = SUBDIR_EXAMPLES
            .iter()
            .find(|(n, _)| *n == name)
            .map(|(_, s)| *s);
        let env = example_env(&name);
        for (key, value) in &env {
            std::env::set_var(key, value);
        }

        let result = generate_for(&example_dir, subdir);

        for (key, _) in &env {
            std::env::remove_var(key);
        }

        let generated = match result {
            Ok(text) => text,
            Err(err) => {
                failures.push(format!("{name}: {err:#}"));
                continue;
            }
        };
        let expected = std::fs::read_to_string(example_dir.join("Shipit")).unwrap();
        if mask_version(&generated) != mask_version(&expected) {
            failures.push(format!("{name}: generated Shipit differs"));
        } else {
            checked += 1;
        }
    }

    eprintln!("goldens: {checked} matched");
    if !failures.is_empty() {
        panic!(
            "{} golden(s) failed:\n{}",
            failures.len(),
            failures.join("\n")
        );
    }
    assert_eq!(checked, EXPECTED_GOLDENS);
}

fn generate_for(workspace: &Path, subdir: Option<&str>) -> anyhow::Result<String> {
    let tmp = tempfile::tempdir()?;
    let out = tmp.path().join("Shipit.generated");
    let mut command = std::process::Command::new(env!("CARGO_BIN_EXE_shipit"));
    command.arg("generate").arg(workspace);
    if let Some(subdir) = subdir {
        command.args(["--subdir", subdir]);
    }
    command.arg("--out").arg(&out);
    // Env vars set by the caller are inherited.
    let output = command.output()?;
    if !output.status.success() {
        anyhow::bail!(
            "generate failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );
    }
    Ok(std::fs::read_to_string(&out)?)
}
