//! Shipit file generation (port of `generator.py`).

use std::path::Path;

use anyhow::{anyhow, Result};

/// The bundled Python version file is the single version source while the
/// two implementations coexist.
const VERSION_PY: &str = include_str!("../../../src/shipit/version.py");

pub fn shipit_version() -> &'static str {
    static VERSION: std::sync::OnceLock<String> = std::sync::OnceLock::new();
    VERSION.get_or_init(|| {
        VERSION_PY
            .lines()
            .find_map(|line| {
                let rest = line.strip_prefix("version = \"")?;
                rest.split('"').next().map(str::to_owned)
            })
            .unwrap_or_else(|| "0.0.0".to_owned())
    })
}

pub struct Entrypoint {
    pub build: (&'static str, &'static str),
    pub serve: (&'static str, &'static str),
    /// The deployment identity the generated file passes to the serve when
    /// it differs from the serve function's default.
    pub provider: Option<&'static str>,
}

const STATICFILE_SERVE: (&str, &str) = ("//shipit/tools:staticfile.shipit", "staticfile_serve");

/// Mirror of `STARLARK_ENTRYPOINTS` in generator.py.
pub fn entrypoint(provider: &str) -> Result<Entrypoint> {
    let ep = match provider {
        "python" => Entrypoint {
            build: ("//shipit/tools:python.shipit", "python_build"),
            serve: ("//shipit/tools:python.shipit", "python_serve"),
            provider: None,
        },
        "staticfile" => Entrypoint {
            build: ("//shipit/tools:staticfile.shipit", "staticfile_build"),
            serve: STATICFILE_SERVE,
            provider: None,
        },
        "hugo" => Entrypoint {
            build: ("//shipit/tools:hugo.shipit", "hugo_build"),
            serve: STATICFILE_SERVE,
            provider: Some("hugo"),
        },
        "mkdocs" => Entrypoint {
            build: ("//shipit/tools:mkdocs.shipit", "mkdocs_build"),
            serve: STATICFILE_SERVE,
            provider: Some("mkdocs"),
        },
        "jekyll" => Entrypoint {
            build: ("//shipit/tools:jekyll.shipit", "jekyll_build"),
            serve: STATICFILE_SERVE,
            provider: Some("jekyll"),
        },
        "node-static" => Entrypoint {
            build: ("//shipit/tools:node_static.shipit", "nodestatic_build"),
            serve: STATICFILE_SERVE,
            provider: Some("node-static"),
        },
        "go" => Entrypoint {
            build: ("//shipit/tools:go.shipit", "go_build"),
            serve: ("//shipit/tools:go.shipit", "go_serve"),
            provider: None,
        },
        "php" => Entrypoint {
            build: ("//shipit/tools:php.shipit", "php_build"),
            serve: ("//shipit/tools:php.shipit", "php_serve"),
            provider: None,
        },
        "wordpress" => Entrypoint {
            build: ("//shipit/tools:wordpress.shipit", "wordpress_build"),
            serve: ("//shipit/tools:wordpress.shipit", "wordpress_serve"),
            provider: None,
        },
        "node" => Entrypoint {
            build: ("//shipit/tools:node.shipit", "node_build"),
            serve: ("//shipit/tools:node.shipit", "node_serve"),
            provider: None,
        },
        "laravel" => Entrypoint {
            build: ("//shipit/tools:laravel.shipit", "laravel_build"),
            serve: ("//shipit/tools:laravel.shipit", "laravel_serve"),
            provider: None,
        },
        other => {
            return Err(anyhow!(
                "No Starlark provider entrypoint registered for {other:?}"
            ))
        }
    };
    Ok(ep)
}

/// Port of `generate_shipit_loader`: byte-identical output.
pub fn generate_shipit_loader(
    entrypoint: &Entrypoint,
    subdir: Option<&str>,
    name: Option<&str>,
) -> String {
    let (build_module, build_function) = entrypoint.build;
    let (serve_module, serve_function) = entrypoint.serve;
    let mut out: Vec<String> = vec![
        format!(
            "# Generated by Shipit v{} — https://github.com/wasmerio/shipit",
            shipit_version()
        ),
        "# This file is yours to edit: add steps or override the serve below.".to_owned(),
        String::new(),
    ];
    if build_module == serve_module {
        out.push(format!(
            "load(\"{build_module}\", \"{build_function}\", \"{serve_function}\")"
        ));
    } else {
        out.push(format!("load(\"{build_module}\", \"{build_function}\")"));
        out.push(format!("load(\"{serve_module}\", \"{serve_function}\")"));
    }
    out.push(String::new());
    if let Some(subdir) = subdir {
        out.push(format!(
            "app_subdir = {}",
            serde_json::to_string(subdir).expect("string serializes")
        ));
        out.push(String::new());
    }
    out.push(format!("build = {build_function}(config)"));
    out.push(String::new());
    let mut serve_args: Vec<String> = vec!["config".to_owned(), "build".to_owned()];
    if let Some(name) = name {
        // Baked in so the serve name doesn't drift with the directory the
        // checkout happens to live in.
        serve_args.push(format!(
            "name = {}",
            serde_json::to_string(name).expect("string serializes")
        ));
    }
    if let Some(provider) = entrypoint.provider {
        serve_args.push(format!("provider = \"{provider}\""));
    }
    out.push(format!("{serve_function}({})", serve_args.join(", ")));
    out.push(String::new());
    out.join("\n")
}

/// Port of `generate_shipit`: entrypoint lookup + the baked name.
pub fn generate_shipit(
    provider: &str,
    config_name: Option<&str>,
    subdir: Option<&str>,
) -> Result<String> {
    let ep = entrypoint(provider)?;
    Ok(generate_shipit_loader(&ep, subdir, config_name))
}

/// Locate the bundled starlib. While the Rust and Python implementations
/// coexist, the Starlark stdlib lives in the Python tree; the embedded
/// variant lands at cutover.
pub fn starlib_dir() -> std::path::PathBuf {
    if let Ok(path) = std::env::var("SHIPIT_STARLIB") {
        return Path::new(&path).to_path_buf();
    }
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../src/shipit/starlib")
        .canonicalize()
        .unwrap_or_else(|_| Path::new("src/shipit/starlib").to_path_buf())
}
