"""CLI behavior differential: Python shipit vs Rust shipit.

For every example, runs `generate` and `plan` through both implementations
and diffs the outputs (generate: version-masked file bytes; plan: parsed
JSON). This is the phase-3 gate and the cutover confidence check.

Usage: uv run python scripts/cli_differential.py [--rust-bin PATH]
"""

import argparse
import json
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
EXAMPLES = ROOT / "examples"

EXAMPLE_ENV = {
    "php-wordpress-empty": {"SHIPIT_WP_VERSION": "latest", "SHIPIT_PHPIX": "true"},
}
SUBDIR_EXAMPLES = {
    "node-npm-file-subdir": "apps/dashboard",
    "node-pnpm-workspace-subdir": "apps/dashboard",
}
VERSION_RE = re.compile(r"^# Generated by Shipit v\S+", re.MULTILINE)


def mask(text: str) -> str:
    return VERSION_RE.sub("# Generated by Shipit v<VERSION>", text)


def run(cmd, env_extra, cwd=ROOT):
    env = os.environ.copy()
    env.update(env_extra)
    return subprocess.run(cmd, capture_output=True, text=True, env=env, cwd=cwd)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--rust-bin",
        default=str(ROOT / "target" / "debug" / "shipit"),
        help="Path to the Rust shipit binary",
    )
    parser.add_argument("--only", help="Only run examples containing this substring")
    args = parser.parse_args()

    failures: list[str] = []
    checked = 0

    for example in sorted(EXAMPLES.iterdir()):
        if not (example / "Shipit").is_file():
            continue
        name = example.name
        if args.only and args.only not in name:
            continue
        env_extra = EXAMPLE_ENV.get(name, {})
        subdir = SUBDIR_EXAMPLES.get(name)
        subdir_args = [f"--subdir={subdir}"] if subdir else []

        with tempfile.TemporaryDirectory() as tmp:
            py_gen = Path(tmp) / "py.Shipit"
            rs_gen = Path(tmp) / "rs.Shipit"
            py = run(
                ["uv", "run", "shipit", "generate", str(example), *subdir_args,
                 "-o", str(py_gen)],
                env_extra,
            )
            rs = run(
                [args.rust_bin, "generate", str(example), *subdir_args,
                 "--out", str(rs_gen)],
                env_extra,
            )
            if py.returncode != rs.returncode:
                failures.append(
                    f"{name}: generate exit codes differ "
                    f"(py={py.returncode}, rs={rs.returncode})\n{rs.stderr[-400:]}"
                )
                continue
            if py.returncode == 0 and mask(py_gen.read_text()) != mask(rs_gen.read_text()):
                failures.append(f"{name}: generated Shipit differs")
                continue

            py_plan = Path(tmp) / "py.plan.json"
            rs_plan = Path(tmp) / "rs.plan.json"
            py = run(
                ["uv", "run", "shipit", "plan", str(example), *subdir_args,
                 "-o", str(py_plan)],
                env_extra,
            )
            rs = run(
                [args.rust_bin, "plan", str(example), *subdir_args,
                 "--out", str(rs_plan)],
                env_extra,
            )
            if py.returncode != rs.returncode:
                failures.append(
                    f"{name}: plan exit codes differ "
                    f"(py={py.returncode}, rs={rs.returncode})\n{rs.stderr[-400:]}"
                )
                continue
            if py.returncode == 0:
                py_data = json.loads(py_plan.read_text())
                rs_data = json.loads(rs_plan.read_text())
                if py_data != rs_data:
                    diff_keys = []
                    for key in set(py_data) | set(rs_data):
                        if py_data.get(key) != rs_data.get(key):
                            diff_keys.append(key)
                    detail = ""
                    if "config" in diff_keys:
                        pc, rc = py_data.get("config", {}), rs_data.get("config", {})
                        fields = sorted(
                            k for k in set(pc) | set(rc) if pc.get(k) != rc.get(k)
                        )
                        detail = f" config fields: {fields[:8]}"
                    failures.append(f"{name}: plan differs in {sorted(diff_keys)}{detail}")
                    continue
        checked += 1

    print(f"cli differential: {checked} examples matched")
    if failures:
        print(f"{len(failures)} failures:")
        for failure in failures[:15]:
            print(f"  - {failure}")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
